
# Other Homebrew packages
brew grep
brew pcre

# Other Cask applications
cask alfred
cask anaconda
cask deepl
cask docker
cask firefox
cask font-fira-code
cask gephi
cask google-chrome
cask google-cloud-sdk
cask hammerspoon
cask kite
cask mendeley
cask microsoft-teams
cask minikube
cask ngrok
cask notion
cask postman
cask slack
cask spotify
cask visual-studio-code
cask xmind
cask xquartz

# App Store applications
appstore 549083868 Display Menu (2.2.3)
appstore 409183694 Keynote (9.1)
appstore 539883307 LINE (5.16.0)
appstore 409203825 Numbers (6.1)
appstore 409201541 Pages (8.1)
appstore 1429033973 RunCat (4.6)
appstore 497799835 Xcode (9.3)
